name: autocal
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  share_handler: ^0.0.25
  receive_sharing_intent: ^1.8.1
  device_calendar: ^4.3.2
  # flutter_local_notifications: ^17.2.3
  # purchases_flutter: ^6.30.2
  speech_to_text: ^7.0.0
  # shared_preferences: ^2.3.2
  intl: ^0.18.0
  flutter_riverpod: ^2.6.1
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.6.1
  permission_handler: ^11.3.1
  path_provider: ^2.1.4
  dio: ^5.9.0
  fvm: ^3.2.1
  flutter_leap_sdk: ^0.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true

  # Assets
  # assets:
  #   - images/

  # Fonts
  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Thin.ttf
          weight: 100
        - asset: assets/fonts/Urbanist-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Urbanist-Light.ttf
          weight: 300
        - asset: assets/fonts/Urbanist-Regular.ttf
          weight: 400
        - asset: assets/fonts/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/Urbanist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Urbanist-Bold.ttf
          weight: 700
        - asset: assets/fonts/Urbanist-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Urbanist-Black.ttf
          weight: 900
        - asset: assets/fonts/Urbanist-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Urbanist-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Urbanist-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Urbanist-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Urbanist-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Urbanist-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Urbanist-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Urbanist-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Urbanist-BlackItalic.ttf
          weight: 900
          style: italic
